@baseUrl = http://localhost:3000


###ControllerGetPessoa
# @name PessoasController
#### Lista todos os pessoa
GET {{baseUrl}}/pessoas/
?limit=10
&offset=10

### Lista apenas uma pessoa
GET {{baseUrl}}/pessoas/3

### Cria uma pessoa
POST {{baseUrl}}/pessoas/
Content-Type: application/json

  {
    "name": "Larissa maques",
    "email": "larie@email.com",
    "password": "1234"
  
  }

### Atualiza uma pessoa
PATCH {{baseUrl}}/pessoas/55e8e752-4d7c-4acf-801e-5dae4ac110c4/
Content-Type: application/json

  {
    "name": "Lucas Santos",
    "email": "lusca@email.com",
    "password": "123456"
  }




##--------------------------------------------##
#Recados

###ControllerGetRecado
# @name RecadosController
#### Lista todos os recados
GET {{baseUrl}}/recados/
?limit=2
&offset=0

### Lista apenas um recado
GET {{baseUrl}}/recados/3

### Cria um recado
POST {{baseUrl}}/recados/
Content-Type: application/json

  {
    "texto": " recado novo",
    "deId": "85c248ba-a300-4a45-9a14-45e57996b4c2",
    "paraId": "a63d3f62-3bc2-4b31-b1d4-cde262da97f1"
  
  }

### Atualiza um recado
PATCH {{baseUrl}}/recados/27f8-17f95952d20d/
Content-Type: application/json

  {
    "texto": "Agora sou o primeiro",
    "de": "Lucas",
    "para": "Lara"
  }

### Deleta um recado
DELETE {{baseUrl}}/recados/6a8d775d-fb27-4f82-920d-44f0c2f68441/

###------------------------------------------------------------###

