@baseUrl = http://localhost:3000

@authToken = {{authenticate.response.body.accessToken}}
@refreshToken ={{authenticate.response.body.refreshToken}}


###ControllerGetPessoa
# @name PessoasController
#### Lista todos os pessoa
GET {{baseUrl}}/pessoas/
?limit=10
&offset=10


### Lista apenas uma pessoa
GET {{baseUrl}}/pessoas/85c248ba-a300-4a45-9a14-45e57996b4c2


### Cria uma pessoa
POST {{baseUrl}}/pessoas/
Content-Type: application/json
Authorization: Bearer {{authToken}}

  {
    "name": "teste",
    "email": "teste@email.com",
    "password": "123456"
  
  }

### Atualiza uma pessoa
PATCH {{baseUrl}}/pessoas/a2a356bf-5e39-49c5-9ff0-a6cdcc79c950
Content-Type: application/json
Authorization: Bearer {{authToken}}

  {
    "name": "Luiz Otávio",
    "email": "luiz@email.com",
    "password": "1234678"
  }

###0
DELETE {{baseUrl}}/pessoas/a2a356bf-5e39-49c5-9ff0-a6cdcc79c950/
Authorization: Bearer {{authToken}}


##--------------------------------------------##
#Recados

###ControllerGetRecado
# @name RecadosController
#### Lista todos os recados
GET {{baseUrl}}/recados/



### Lista apenas um recado
GET {{baseUrl}}/recados/e0cc2c6a-057f-4e83-909f-86fc5e35fa38

### Cria um recado
POST {{baseUrl}}/recados/
Content-Type: application/json
Authorization: Bearer {{authToken}}


  {
    "texto": " reacdo 3",
    "paraId": "55e8e752-4d7c-4acf-801e-5dae4ac110c4",
    "lido": true
  
  }

### Atualiza um recado
PATCH {{baseUrl}}/recados/e0cc2c6a-057f-4e83-909f-86fc5e35fa38
Content-Type: application/json
Authorization: Bearer {{authToken}}

  {
    "texto": ""
  }

### Deleta um recado
DELETE {{baseUrl}}/recados/172d79ed-ea73-4005-8b56-b94d7bab336a
Authorization: Bearer {{authToken}}


###------------------------------------------------------------###

# AUTH
#### Autenticação
# @name authenticate
POST  {{baseUrl}}/auth/
Content-Type: application/json

{
  "email": "pedro@email.com",
  "password": "123456"
}


# Re-Autenticação
#### Autenticação
# @name reAuthenticate
POST  {{baseUrl}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}
